config/routes.rb
Ibetchu::Application.routes.draw do
    
  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

	root :to => 'home#index'
	resources :users
  	resources :password_resets 
	resources :user_sessions
	resources :taglines
	
	match 'login' => 'user_sessions#new', :as => :login
	match 'logout' => 'user_sessions#destroy', :as => :logout  
  	  
   
  
  
  

end

app/models/tagline.rb
class Tagline < ActiveRecord::Base
  attr_accessible :phrase
  
  
  def self.random_phrase
	self.all.sample	
  end
  
  def to_s
  	self.phrase
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :username, :email, :password, :password_confirmation, :password_reset

  validates_length_of :password, :minimum => 3, :message => "password must be at least 3 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :require_login
  
  def not_authenticated
    redirect_to root_path, :alert => "Please login first."
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :require_login
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login
    
  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create 
    @user = User.find_by_email(params[:email])
        
    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user
        
    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end
    
  # This is the reset password form.
  def edit
    @user = User.load_from_reset_password_token(params[:id])
    @token = params[:id]
    not_authenticated unless @user
  end
      
  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:token]
    @user = User.load_from_reset_password_token(params[:token])
    not_authenticated unless @user
    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/taglines_controller.rb
class TaglinesController < ApplicationController
  # GET /taglines
  # GET /taglines.json
  def index
    @taglines = Tagline.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @taglines }
    end
  end

  # GET /taglines/1
  # GET /taglines/1.json
  def show
    @tagline = Tagline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tagline }
    end
  end

  # GET /taglines/new
  # GET /taglines/new.json
  def new
    @tagline = Tagline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tagline }
    end
  end

  # GET /taglines/1/edit
  def edit
    @tagline = Tagline.find(params[:id])
  end

  # POST /taglines
  # POST /taglines.json
  def create
    @tagline = Tagline.new(params[:tagline])

    respond_to do |format|
      if @tagline.save
        format.html { redirect_to @tagline, notice: 'Tagline was successfully created, You Rock!' }
        format.json { render json: @tagline, status: :created, location: @tagline }
      else
        format.html { render action: "new" }
        format.json { render json: @tagline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /taglines/1
  # PUT /taglines/1.json
  def update
    @tagline = Tagline.find(params[:id])

    respond_to do |format|
      if @tagline.update_attributes(params[:tagline])
        format.html { redirect_to @tagline, notice: 'Tagline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tagline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taglines/1
  # DELETE /taglines/1.json
  def destroy
    @tagline = Tagline.find(params[:id])
    @tagline.destroy

    respond_to do |format|
      format.html { redirect_to taglines_url }
      format.json { head :no_content }
    end
  
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]
  def new
    @user = User.new
  end
  
  def create
    respond_to do |format|
      if @user = login(params[:username],params[:password], params[:remember])
        format.html { redirect_back_or_to(:users, :notice => 'Login successful.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { flash.now[:alert] = "Login Pooched... Sad Face."; render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
    
  def destroy
    logout
    redirect_to(:users, :notice => 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
 
  skip_before_filter :require_login, :only => [:index, :new, :create, :activate]
  
  def activate 
  	if (@user = User.load_from_activation_token([:id]))
      @user.activate!
      redirect_to(login_path, :notice => 'User Successfully Activated, go forth and motivate!')
    else
   	  not_authenticated
    end
  end
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/taglines_helper.rb
module TaglinesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
TEST

app/views/home/index.html.erb
<div id="picture">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iBetcha | The Social Motivator</title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "application" %>
      <%= javascript_include_tag "modernizr.custom.80028.js" %>
      <%= csrf_meta_tags %>
      
  </head>
  
  <body>
   <div id="note">
    <p id=""><%= notice %></p>
    <p id=""><%= alert %></p>
    
    <a id="close">[close]</a>
  </div>
  
  <div id="user_nav">
    <% if current_user %>
      Hi <%= current_user.username %>, <%= Tagline.random_phrase %>
      <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
      <%= link_to "Logout", :logout %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>
  </div>
  
  <div id="main_container">
  
  <%= yield %>
  
  </div>
  
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
  <script>
   $("#close").click(function() {
     $("#note").hide();
   });
  </script>
    
  </body>
</html>

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<h1>Choose a new password</h1>
<%= form_for @user, :url => password_reset_path(@user), :html => {:method => :put} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= f.label :email %><br />
    <%= @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
    <%= hidden_field_tag :token, @token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/taglines/_form.html.erb
<%= form_for(@tagline) do |f| %>
  <% if @tagline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tagline.errors.count, "error") %> prohibited this tagline from being saved:</h2>

      <ul>
      <% @tagline.errors.full_messages.each do |msg| %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phrase %><br />
    <%= f.text_field :phrase %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taglines/edit.html.erb
<h1>Editing tagline</h1>

<%= render 'form' %>

<%= link_to 'Show', @tagline %> |
<%= link_to 'Back', taglines_path %>

app/views/taglines/index.html.erb
<h1>Listing taglines</h1>

<table>
  <tr>
    <th>Phrase</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @taglines.each do |tagline| %>
  <tr>
    <td><%= tagline.phrase %></td>
    <td><%= link_to 'Show', tagline %></td>
    <td><%= link_to 'Edit', edit_tagline_path(tagline) %></td>
    <td><%= link_to 'Destroy', tagline, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tagline', new_tagline_path %>

app/views/taglines/new.html.erb
<h1>New tagline</h1>

<%= render 'form' %>

<%= link_to 'Back', taglines_path %>

app/views/taglines/show.html.erb
<p>
  <b>Phrase:</b>
  <%= @tagline.phrase %>
</p>


<%= link_to 'Edit', edit_tagline_path(@tagline) %> |
<%= link_to 'Back', taglines_path %>

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :username %><br />
    <%= text_field_tag :username %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
	<div class="field">
		<%= check_box_tag :remember_me, 1, params[:remember_me] %>
		<%= label_tag :remember_me %>
	
	
	</div> 
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
    
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Forgot Password?', new_password_reset_path %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
     <%= f.label :password %><br />
     <%= f.password_field :password %>
  </div>
  <div class="field">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>